// Code generated by goctl. DO NOT EDIT.
package types

type Product struct {
	Id           int64  `json:"id"`
	ProductName  string `json:"product_name"`
	ProductNum   int64  `json:"product_num"`
	ProductImage string `json:"product_image"`
	ProductUrl   string `json:"product_url"`
	CreateTime   int64  `json:"create_time"`
	UpdateTime   int64  `json:"update_time"`
	DeleteTime   int64  `json:"delete_time"`
	DelState     int64  `json:"del_state"`
	Version      int64  `json:"version"`
}

type GetProductInfoReq struct {
	Id int64 `path:"id"`
}

type GetProductInfoResp struct {
	Id           int64  `json:"id"`
	ProductName  string `json:"product_name"`
	ProductNum   int64  `json:"product_num"`
	ProductImage string `json:"product_image"`
	ProductUrl   string `json:"product_url"`
	CreateTime   int64  `json:"create_time"`
	UpdateTime   int64  `json:"update_time"`
	DeleteTime   int64  `json:"delete_time"`
	DelState     int64  `json:"del_state"`
	Version      int64  `json:"version"`
}

type CreateProductReq struct {
	Id           int64  `json:"id"`
	ProductName  string `json:"product_name"`
	ProductNum   int64  `json:"product_num"`
	ProductImage string `json:"product_image"`
	ProductUrl   string `json:"product_url"`
	CreateTime   int64  `json:"create_time"`
	UpdateTime   int64  `json:"update_time"`
	DeleteTime   int64  `json:"delete_time"`
	DelState     int64  `json:"del_state"`
	Version      int64  `json:"version"`
}

type CreateProductResp struct {
}

type UpdateProductReq struct {
	Id           int64  `json:"id"`
	ProductName  string `json:"product_name"`
	ProductNum   int64  `json:"product_num"`
	ProductImage string `json:"product_image"`
	ProductUrl   string `json:"product_url"`
	CreateTime   int64  `json:"create_time"`
	UpdateTime   int64  `json:"update_time"`
	DeleteTime   int64  `json:"delete_time"`
	DelState     int64  `json:"del_state"`
	Version      int64  `json:"version"`
}

type UpdateProductResp struct {
}

type DeleteProductReq struct {
	Id int64 `json:"id"`
}

type DeleteProductResp struct {
}

type GetProductListReq struct {
}

type GetProductListResp struct {
	List []*product `json:"list"`
}

type Order struct {
	Id            int64  `json:"id"`
	RoleId        int64  `json:"roleId"`
	Uid           string `json:"uid"`
	Name          string `json:"name"`          // 用户名
	Nickname      string `json:"nickname"`      // 昵称
	Email         string `json:"email"`         // 邮箱
	Mobile        string `json:"mobile"`        // 电话
	Password      string `json:"password"`      // 密码
	Sex           int64  `json:"sex"`           // 性别 0:女 1:男
	Avatar        string `json:"avatar"`        // 头像地址
	WechatUnionid string `json:"wechatUnionid"` // 微信用户唯一ID
	FacebookId    string `json:"facebookId"`    // facebook用户唯一ID
	AppleId       string `json:"appleId"`       // apple用户唯一ID
	Version       int64  `json:"version"`       // 版本号
	State         int64  `json:"state"`
	CreateTime    int64  `json:"createTime"`
	UpdateTime    int64  `json:"updateTime"`
}

type OrderDetailReq struct {
}

type OrderDetailResp struct {
	Id            int64  `json:"id"`
	RoleId        int64  `json:"roleId"`
	Uid           string `json:"uid"`
	Name          string `json:"name"`          // 用户名
	Nickname      string `json:"nickname"`      // 昵称
	Email         string `json:"email"`         // 邮箱
	Mobile        string `json:"mobile"`        // 电话
	Password      string `json:"password"`      // 密码
	Sex           int64  `json:"sex"`           // 性别 0:女 1:男
	Avatar        string `json:"avatar"`        // 头像地址
	WechatUnionid string `json:"wechatUnionid"` // 微信用户唯一ID
	FacebookId    string `json:"facebookId"`    // facebook用户唯一ID
	AppleId       string `json:"appleId"`       // apple用户唯一ID
	Version       int64  `json:"version"`       // 版本号
	State         int64  `json:"state"`
	CreateTime    int64  `json:"createTime"`
	UpdateTime    int64  `json:"updateTime"`
}

type OrderBindReq struct {
	Email  *string `json:"email,optional"`
	Mobile *string `json:"mobile,optional"`
}

type OrderBindResp struct {
}

type OrderLogoutReq struct {
	Authorization string `header:"Authorization"`
}

type OrderLogoutResp struct {
}

type OrderListReq struct {
	Uid      string `form:"uid,optional"`
	Name     string `form:"name,optional"`
	Nickname string `form:"nickname,optional"`
	Email    string `form:"email,optional"`
	Mobile   string `form:"mobile,optional"`
	Current  int64  `form:"current,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
	Sort     string `form:"sort,default=id desc"`
}

type OrderListResp struct {
	List     []order `json:"list"`
	Total    int64   `json:"total"`    //总数
	Current  int64   `json:"current"`  //当前页
	PageSize int64   `json:"pageSize"` //分页数量
}

type GetOrderInfoReq struct {
	Id int `path:"id"`
}

type GetOrderInfoResp struct {
	Id            int64  `json:"id"`
	RoleId        int64  `json:"roleId"`
	Uid           string `json:"uid"`
	Name          string `json:"name"`          // 用户名
	Nickname      string `json:"nickname"`      // 昵称
	Email         string `json:"email"`         // 邮箱
	Mobile        string `json:"mobile"`        // 电话
	Password      string `json:"password"`      // 密码
	Sex           int64  `json:"sex"`           // 性别 0:女 1:男
	Avatar        string `json:"avatar"`        // 头像地址
	WechatUnionid string `json:"wechatUnionid"` // 微信用户唯一ID
	FacebookId    string `json:"facebookId"`    // facebook用户唯一ID
	AppleId       string `json:"appleId"`       // apple用户唯一ID
	Version       int64  `json:"version"`       // 版本号
	State         int64  `json:"state"`
	CreateTime    int64  `json:"createTime"`
	UpdateTime    int64  `json:"updateTime"`
}

type CreateOrderReq struct {
	Id            int64  `json:"id"`
	RoleId        int64  `json:"roleId"`
	Uid           string `json:"uid"`
	Name          string `json:"name"`          // 用户名
	Nickname      string `json:"nickname"`      // 昵称
	Email         string `json:"email"`         // 邮箱
	Mobile        string `json:"mobile"`        // 电话
	Password      string `json:"password"`      // 密码
	Sex           int64  `json:"sex"`           // 性别 0:女 1:男
	Avatar        string `json:"avatar"`        // 头像地址
	WechatUnionid string `json:"wechatUnionid"` // 微信用户唯一ID
	FacebookId    string `json:"facebookId"`    // facebook用户唯一ID
	AppleId       string `json:"appleId"`       // apple用户唯一ID
	Version       int64  `json:"version"`       // 版本号
	State         int64  `json:"state"`
	CreateTime    int64  `json:"createTime"`
	UpdateTime    int64  `json:"updateTime"`
}

type CreateOrderResp struct {
}

type UpdateOrderReq struct {
	Id            int64  `json:"id"`
	RoleId        int64  `json:"roleId"`
	Uid           string `json:"uid"`
	Name          string `json:"name"`          // 用户名
	Nickname      string `json:"nickname"`      // 昵称
	Email         string `json:"email"`         // 邮箱
	Mobile        string `json:"mobile"`        // 电话
	Password      string `json:"password"`      // 密码
	Sex           int64  `json:"sex"`           // 性别 0:女 1:男
	Avatar        string `json:"avatar"`        // 头像地址
	WechatUnionid string `json:"wechatUnionid"` // 微信用户唯一ID
	FacebookId    string `json:"facebookId"`    // facebook用户唯一ID
	AppleId       string `json:"appleId"`       // apple用户唯一ID
	Version       int64  `json:"version"`       // 版本号
	State         int64  `json:"state"`
	CreateTime    int64  `json:"createTime"`
	UpdateTime    int64  `json:"updateTime"`
}

type UpdateOrderResp struct {
}

type DeleteOrderReq struct {
	Id int `json:"id"`
}

type DeleteOrderResp struct {
}

type GetOrderListReq struct {
	Current  int64 `json:"current"`  //当前页
	PageSize int64 `json:"pageSize"` //分页数量
}

type GetOrderListResp struct {
	List     []*order `json:"list"`
	Total    int64    `json:"total"`    //总数
	Current  int64    `json:"current"`  //当前页
	PageSize int64    `json:"pageSize"` //分页数量
}

type User struct {
	Id            int64  `json:"id"`
	RoleId        int64  `json:"roleId"`
	Uid           string `json:"uid"`
	Name          string `json:"name"`          // 用户名
	Nickname      string `json:"nickname"`      // 昵称
	Email         string `json:"email"`         // 邮箱
	Mobile        string `json:"mobile"`        // 电话
	Password      string `json:"password"`      // 密码
	Sex           int64  `json:"sex"`           // 性别 0:女 1:男
	Avatar        string `json:"avatar"`        // 头像地址
	WechatUnionid string `json:"wechatUnionid"` // 微信用户唯一ID
	FacebookId    string `json:"facebookId"`    // facebook用户唯一ID
	AppleId       string `json:"appleId"`       // apple用户唯一ID
	Version       int64  `json:"version"`       // 版本号
	State         int64  `json:"state"`
	CreateTime    int64  `json:"createTime"`
	UpdateTime    int64  `json:"updateTime"`
}

type UserDetailReq struct {
}

type UserDetailResp struct {
	Id            int64  `json:"id"`
	RoleId        int64  `json:"roleId"`
	Uid           string `json:"uid"`
	Name          string `json:"name"`          // 用户名
	Nickname      string `json:"nickname"`      // 昵称
	Email         string `json:"email"`         // 邮箱
	Mobile        string `json:"mobile"`        // 电话
	Password      string `json:"password"`      // 密码
	Sex           int64  `json:"sex"`           // 性别 0:女 1:男
	Avatar        string `json:"avatar"`        // 头像地址
	WechatUnionid string `json:"wechatUnionid"` // 微信用户唯一ID
	FacebookId    string `json:"facebookId"`    // facebook用户唯一ID
	AppleId       string `json:"appleId"`       // apple用户唯一ID
	Version       int64  `json:"version"`       // 版本号
	State         int64  `json:"state"`
	CreateTime    int64  `json:"createTime"`
	UpdateTime    int64  `json:"updateTime"`
}

type UserBindReq struct {
	Email  *string `json:"email,optional"`
	Mobile *string `json:"mobile,optional"`
}

type UserBindResp struct {
}

type UserLogoutReq struct {
	Authorization string `header:"Authorization"`
}

type UserLogoutResp struct {
}

type UserListReq struct {
	Uid      string `form:"uid,optional"`
	Name     string `form:"name,optional"`
	Nickname string `form:"nickname,optional"`
	Email    string `form:"email,optional"`
	Mobile   string `form:"mobile,optional"`
	Current  int64  `form:"current,default=1"`
	PageSize int64  `form:"pageSize,default=20"`
	Sort     string `form:"sort,default=id desc"`
}

type UserListResp struct {
	List     []User `json:"list"`
	Total    int64  `json:"total"`    //总数
	Current  int64  `json:"current"`  //当前页
	PageSize int64  `json:"pageSize"` //分页数量
}

type GetUserInfoReq struct {
	Id int `path:"id"`
}

type GetUserInfoResp struct {
	Id            int64  `json:"id"`
	RoleId        int64  `json:"roleId"`
	Uid           string `json:"uid"`
	Name          string `json:"name"`          // 用户名
	Nickname      string `json:"nickname"`      // 昵称
	Email         string `json:"email"`         // 邮箱
	Mobile        string `json:"mobile"`        // 电话
	Password      string `json:"password"`      // 密码
	Sex           int64  `json:"sex"`           // 性别 0:女 1:男
	Avatar        string `json:"avatar"`        // 头像地址
	WechatUnionid string `json:"wechatUnionid"` // 微信用户唯一ID
	FacebookId    string `json:"facebookId"`    // facebook用户唯一ID
	AppleId       string `json:"appleId"`       // apple用户唯一ID
	Version       int64  `json:"version"`       // 版本号
	State         int64  `json:"state"`
	CreateTime    int64  `json:"createTime"`
	UpdateTime    int64  `json:"updateTime"`
}

type CreateUserReq struct {
	Id            int64  `json:"id"`
	RoleId        int64  `json:"roleId"`
	Uid           string `json:"uid"`
	Name          string `json:"name"`          // 用户名
	Nickname      string `json:"nickname"`      // 昵称
	Email         string `json:"email"`         // 邮箱
	Mobile        string `json:"mobile"`        // 电话
	Password      string `json:"password"`      // 密码
	Sex           int64  `json:"sex"`           // 性别 0:女 1:男
	Avatar        string `json:"avatar"`        // 头像地址
	WechatUnionid string `json:"wechatUnionid"` // 微信用户唯一ID
	FacebookId    string `json:"facebookId"`    // facebook用户唯一ID
	AppleId       string `json:"appleId"`       // apple用户唯一ID
	Version       int64  `json:"version"`       // 版本号
	State         int64  `json:"state"`
	CreateTime    int64  `json:"createTime"`
	UpdateTime    int64  `json:"updateTime"`
}

type CreateUserResp struct {
}

type UpdateUserReq struct {
	Id            int64  `json:"id"`
	RoleId        int64  `json:"roleId"`
	Uid           string `json:"uid"`
	Name          string `json:"name"`          // 用户名
	Nickname      string `json:"nickname"`      // 昵称
	Email         string `json:"email"`         // 邮箱
	Mobile        string `json:"mobile"`        // 电话
	Password      string `json:"password"`      // 密码
	Sex           int64  `json:"sex"`           // 性别 0:女 1:男
	Avatar        string `json:"avatar"`        // 头像地址
	WechatUnionid string `json:"wechatUnionid"` // 微信用户唯一ID
	FacebookId    string `json:"facebookId"`    // facebook用户唯一ID
	AppleId       string `json:"appleId"`       // apple用户唯一ID
	Version       int64  `json:"version"`       // 版本号
	State         int64  `json:"state"`
	CreateTime    int64  `json:"createTime"`
	UpdateTime    int64  `json:"updateTime"`
}

type UpdateUserResp struct {
}

type DeleteUserReq struct {
	Id int `json:"id"`
}

type DeleteUserResp struct {
}

type GetUserListReq struct {
	Current  int64 `json:"current"`  //当前页
	PageSize int64 `json:"pageSize"` //分页数量
}

type GetUserListResp struct {
	List     []*User `json:"list"`
	Total    int64   `json:"total"`    //总数
	Current  int64   `json:"current"`  //当前页
	PageSize int64   `json:"pageSize"` //分页数量
}

type CheckProductReq struct {
}

type CheckProductResp struct {
	PageSize int64 `json:"pageSize"` //分页数量
}
