// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"looklook/common/globalkey"
	"looklook/common/xerr"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productFieldNames          = builder.RawFieldNames(&Product{})
	productRows                = strings.Join(productFieldNames, ",")
	productRowsExpectAutoSet   = strings.Join(stringx.Remove(productFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	productRowsWithPlaceHolder = strings.Join(stringx.Remove(productFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"

	cacheZwzmicroShopProductIdPrefix = "cache:zwzmicroShop:product:id:"
)

type (
	productModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *Product) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Product, error)
		Update(ctx context.Context, session sqlx.Session, data *Product) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *Product) error
		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultProductModel struct {
		sqlc.CachedConn
		table string
	}

	Product struct {
		Id           int64          `db:"id"`
		ProductName  sql.NullString `db:"product_name"`
		ProductNum   sql.NullInt64  `db:"product_num"`
		ProductImage sql.NullString `db:"product_image"`
		ProductUrl   sql.NullString `db:"product_url"`
		CreateTime   time.Time      `db:"create_time"`
		UpdateTime   time.Time      `db:"update_time"`
		DeleteTime   time.Time      `db:"delete_time"`
		DelState     int64          `db:"del_state"`
		Version      int64          `db:"version"`
	}
)

func newProductModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultProductModel {
	return &defaultProductModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`product`",
	}
}

func (m *defaultProductModel) Insert(ctx context.Context, session sqlx.Session, data *Product) (sql.Result, error) {
	data.DeleteTime = time.Unix(0, 0)
	zwzmicroShopProductIdKey := fmt.Sprintf("%s%v", cacheZwzmicroShopProductIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, productRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.ProductName, data.ProductNum, data.ProductImage, data.ProductUrl, data.DeleteTime, data.DelState, data.Version)
		}
		return conn.ExecCtx(ctx, query, data.ProductName, data.ProductNum, data.ProductImage, data.ProductUrl, data.DeleteTime, data.DelState, data.Version)
	}, zwzmicroShopProductIdKey)
}

func (m *defaultProductModel) FindOne(ctx context.Context, id int64) (*Product, error) {
	zwzmicroShopProductIdKey := fmt.Sprintf("%s%v", cacheZwzmicroShopProductIdPrefix, id)
	var resp Product
	err := m.QueryRowCtx(ctx, &resp, zwzmicroShopProductIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", productRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductModel) Update(ctx context.Context, session sqlx.Session, data *Product) (sql.Result, error) {
	zwzmicroShopProductIdKey := fmt.Sprintf("%s%v", cacheZwzmicroShopProductIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, productRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.ProductName, data.ProductNum, data.ProductImage, data.ProductUrl, data.DeleteTime, data.DelState, data.Version, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.ProductName, data.ProductNum, data.ProductImage, data.ProductUrl, data.DeleteTime, data.DelState, data.Version, data.Id)
	}, zwzmicroShopProductIdKey)
}

func (m *defaultProductModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, data *Product) error {

	oldVersion := data.Version
	data.Version += 1

	var sqlResult sql.Result
	var err error

	zwzmicroShopProductIdKey := fmt.Sprintf("%s%v", cacheZwzmicroShopProductIdPrefix, data.Id)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, productRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, data.ProductName, data.ProductNum, data.ProductImage, data.ProductUrl, data.DeleteTime, data.DelState, data.Version, data.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, data.ProductName, data.ProductNum, data.ProductImage, data.ProductUrl, data.DeleteTime, data.DelState, data.Version, data.Id, oldVersion)
	}, zwzmicroShopProductIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return xerr.NewErrCode(xerr.DB_UPDATE_AFFECTED_ZERO_ERROR)
	}

	return nil
}

func (m *defaultProductModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	zwzmicroShopProductIdKey := fmt.Sprintf("%s%v", cacheZwzmicroShopProductIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, zwzmicroShopProductIdKey)
	return err
}

func (m *defaultProductModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheZwzmicroShopProductIdPrefix, primary)
}
func (m *defaultProductModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", productRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.DelStateNo)
}

func (m *defaultProductModel) tableName() string {
	return m.table
}
